const constants = {
  "ADD_ERROR": "ADD_ERROR",
  "CLEAR_ERROR": "CLEAR_ERROR",
  "SEARCH_ENTITIES": "SEARCH_ENTITIES",
  "RECEIVED_SEARCH_ENTITIES": "RECEIVED_SEARCH_ENTITIES",
  "SEARCH_ENTITIES_LOADING": "SEARCH_ENTITIES_LOADING",
  "CANCEL_SEARCH": "CANCEL_SEARCH",
  "NAVIGATE_AWAY": "NAVIGATE_AWAY",
  "ADD_PERSON": "ADD_PERSON",
  "UPDATE_PERSON_PROP": "UPDATE_PERSON_PROP",
  "REPLACE_PEOPLE": "REPLACE_PEOPLE"
};

export default constants;